#!/usr/bin/env python
"""CodeIT Sums Problem"""
from itertools import combinations
nums = [1,2,6,3,17,82,23,234]
target = 3
def CombinationSums(nums, target):
    ind = []
    all_combinations = []
    #find all combinations
    for i in range(1, len(nums)):
        all_combinations += list(combinations(nums, i))
    for i in range(len(all_combinations)):
        if sum(all_combinations[i]) == target:
        #return index if sum match
            for j in range(len(all_combinations[i])):
                ind.append(nums.index(all_combinations[i][j]))
            return ind
print(CombinationSums(nums, target))
